### ISSUE TITLE
Typo in command title

### ISSUE THREAD

**Issue by BinToss** [harrydowning/swap-tsconfig#10]
![image](https://github.com/harrydowning/swap-tsconfig/assets/7243190/f628fd24-9ee1-47ce-b476-d7686e400dac)
https://github.com/harrydowning/swap-tsconfig/blob/52745491b1f90eecdbbce9ee497ce0f354ce1ea0/package.json#L36

**Comment by harrydowning** [comment]
Thanks for raising this. Will get this fixed.

**Comment by harrydowning** [comment]
Fixed in https://github.com/harrydowning/swap-tsconfig/pull/11
